### ISSUE TITLE
Elitec doesn't work in https://ergogen.cache.works, have to replace with promicro.

### ISSUE THREAD

**Issue by machetie** [adamwulf/chili58#1]
I get an error when i paste the yml 
Error: Field "pcbs.chili58.footprints.mcu.type" should be one of [alps, button, choc, chocmini, diode, jstph, jumper, mx, oled, omron, pad, promicro, rgb, rotary, scrollwheel, slider, trrs, via]

**Comment by adamwulf** [comment]
ah! yes, I'm using a fork of ergogen that includes an elite-c footprint. To fix it for the web version, just replace the `elitec` with `promicro` and it'll work. Note that I'm only partially done with this design, so the key matrix is likely wrong and the rest of the wiring isn't done either, but that'll at least let you see the layout i'm aiming for.
